// <auto-generated />
using System;
using FuerzaCivil.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FuerzaCivil.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627220000_AddSolicitudUbicacion")]
    partial class AddSolicitudUbicacion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuerzaCivil.Api.Models.ConfigApp", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("LatitudDefault")
                        .HasColumnType("double precision");

                    b.Property<double>("LongitudDefault")
                        .HasColumnType("double precision");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ZoomDefault")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("config_app", (string)null);
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.Donacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadNueva")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Donante")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PuntoInteresId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InsumoId");

                    b.HasIndex("PuntoInteresId");

                    b.ToTable("donaciones", (string)null);
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.Insumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadNecesaria")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PuntoInteresId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PuntoInteresId");

                    b.ToTable("insumos", (string)null);
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.PuntoInteres", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Beneficiarios")
                        .HasColumnType("integer");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DonacionesRecibidas")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EstadoOperativo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.PrimitiveCollection<string[]>("TiposDonacion")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Point>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("geography(Point, 4326)");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Tipo");

                    b.HasIndex("Ubicacion");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Ubicacion"), "GIST");

                    b.ToTable("puntos_interes", (string)null);
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AccesoGlobal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.Solicitud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CantidadSolicitada")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("InsumoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotasInternas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProductoNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PuntoInteresId")
                        .HasColumnType("uuid");

                    b.Property<string>("Solicitante")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TelefonoSolicitante")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Point>("Ubicacion")
                        .HasColumnType("geography(Point, 4326)");

                    b.Property<string>("Unidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Estado");

                    b.HasIndex("InsumoId");

                    b.HasIndex("PuntoInteresId");

                    b.HasIndex("Tipo");

                    b.HasIndex("Ubicacion");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Ubicacion"), "GIST");

                    b.ToTable("solicitudes", (string)null);
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.UserPuntoInteres", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PuntoInteresId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "PuntoInteresId");

                    b.HasIndex("PuntoInteresId");

                    b.ToTable("user_pois", (string)null);
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.ZonaAfectada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Intensidad")
                        .HasColumnType("double precision");

                    b.Property<double>("RadioKm")
                        .HasColumnType("double precision");

                    b.Property<string>("ReportadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Point>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("geography(Point, 4326)");

                    b.HasKey("Id");

                    b.HasIndex("Ubicacion");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Ubicacion"), "GIST");

                    b.ToTable("zonas_afectadas", (string)null);
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.Donacion", b =>
                {
                    b.HasOne("FuerzaCivil.Api.Models.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FuerzaCivil.Api.Models.PuntoInteres", "PuntoInteres")
                        .WithMany()
                        .HasForeignKey("PuntoInteresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("PuntoInteres");
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.Insumo", b =>
                {
                    b.HasOne("FuerzaCivil.Api.Models.PuntoInteres", "PuntoInteres")
                        .WithMany("Insumos")
                        .HasForeignKey("PuntoInteresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoInteres");
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.Solicitud", b =>
                {
                    b.HasOne("FuerzaCivil.Api.Models.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FuerzaCivil.Api.Models.PuntoInteres", "PuntoInteres")
                        .WithMany()
                        .HasForeignKey("PuntoInteresId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Insumo");

                    b.Navigation("PuntoInteres");
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.User", b =>
                {
                    b.HasOne("FuerzaCivil.Api.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.UserPuntoInteres", b =>
                {
                    b.HasOne("FuerzaCivil.Api.Models.PuntoInteres", "PuntoInteres")
                        .WithMany()
                        .HasForeignKey("PuntoInteresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuerzaCivil.Api.Models.User", "User")
                        .WithMany("UserPuntosInteres")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoInteres");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.PuntoInteres", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FuerzaCivil.Api.Models.User", b =>
                {
                    b.Navigation("UserPuntosInteres");
                });
#pragma warning restore 612, 618
        }
    }
}

